CREATE TABLE IF NOT EXISTS DWD_TBL_TR_DPACT
(
    DAY_ID date COMMENT '数据日期',
    FK_SAACN_KEY varchar(28) COMMENT '内部账号',
    SA_DDP_ACCT_NO_DET_N varchar(7) COMMENT '活存帐户明细号',
    SATXN_DB_TIMESTAMP decimal(15,0) COMMENT '交易明细时间戳',
    SA_CURR_COD varchar(2) COMMENT '币别',
    SA_OPR_NO varchar(12) COMMENT '操作员号',
    SA_CURR_IDEN varchar(1) COMMENT '钞汇鉴别',
    SA_EC_FLG varchar(1) COMMENT '冲正标志',
    SA_EC_DET_NO_N varchar(7) COMMENT '冲正明细号(数字)',
    SA_CR_AMT decimal(15,2) COMMENT '贷方发生额',
    SA_DDP_ACCT_BAL decimal(15,2) COMMENT '活存帐户余额',
    SA_TX_AMT decimal(15,2) COMMENT '交易金额(TX)',
    SA_TX_CRD_NO varchar(19) COMMENT '交易卡号',
    SA_TX_TYP varchar(1) COMMENT '交易类别',
    SA_TX_LOG_NO varchar(19) COMMENT '交易流水号',
    SA_DR_AMT decimal(15,2) COMMENT '借方发生额',
    SA_DOC_NO varchar(16) COMMENT '凭证号码',
    SA_DOC_TYP varchar(4) COMMENT '凭证种类(DOC)',
    SA_VAL_DT varchar(8) COMMENT '起息日(VAL)',
    SA_SVC decimal(15,2) COMMENT '手续费',
    SA_AUTH_NO varchar(6) COMMENT '授权号',
    SA_CUST_DOCAG_STNO varchar(15) COMMENT '商户交单套号',
    SA_OPUN_COD varchar(9) COMMENT '营业单位代码',
    SA_DSCRP_COD varchar(4) COMMENT '摘要代码',
    SA_RMRK varchar(60) COMMENT '备注',
    SA_TX_TM varchar(9) COMMENT '交易时间',
    SA_TX_DT varchar(8) COMMENT '交易日期（非GRP）',
    SA_SYS_DT varchar(8) COMMENT '系统日期',
    SA_DDP_PDT decimal(15,2) COMMENT '活存积数',
    SA_APP_TX_CODE varchar(4) COMMENT '交易代码(APP)',
    SA_ETX_FLG varchar(1) COMMENT '明细扩展标志',
    SA_OTX_FLG varchar(1) COMMENT '境外消费明细扩展标志',
    SA_FLX_FLG varchar(1) COMMENT '跟单标志(FLX)',
    SA_GUIJI_FLAG varchar(1) COMMENT '集团客户母公司归集类交易',
    SA_PRT_FLG varchar(1) COMMENT '打印标志',
    SA_FILLER varchar(1) COMMENT '分隔符',
    SA_RMRK_1 varchar(40) COMMENT '备注-1',
    SA_OP_CUST_NAME VARCHAR COMMENT '对方户名',
    SA_OP_ACCT_NO varchar(32) COMMENT '对方账号',
    SA_OP_BANK_NO varchar(14) COMMENT '对方行号',
    SA_TX_OD_AMT decimal(15,2) COMMENT '透支金额',
    SA_CHANNEL_FLAG varchar(2) COMMENT '交易渠道',
    CM_CHANNEL_DSCRP varchar(20) COMMENT '交易渠道描述',
    SA_EXTER_SYS_ID varchar(4) COMMENT '系统编号',
    SA_EXTER_SUB_SYS_ID varchar(4) COMMENT '子系统编号',
    SA_SPV_A varchar(12) COMMENT 'A级授权柜员',
    SA_SPV_B varchar(12) COMMENT 'B级授权柜员',
    PRIMARY KEY(DAY_ID,FK_SAACN_KEY,SA_DDP_ACCT_NO_DET_N) NOT ENFORCED
)
WITH(
    'connector'='starrocks', 
    'jdbc-url'='jdbc:mysql://172.18.244.74:18030', 
    'scan-url'='172.18.244.74:19030', 
    'load-url'='172.18.244.74:18030,172.18.244.75:18030,172.18.244.75:18030', 
    'username'='root', 
    'password'='datacanvas', 
    'database-name'='rtdsp', 
    'table-name'='DWD_TBL_TR_DPACT' 
);
